server:
  port: 8084

spring:
  application:
    name: payment-processor
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: kafka-check
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: payment-processor-group
      auto-offset-reset: earliest # Starts consumption from earliest offset for new consumer groups.
      max-poll-records: 100 # Batches up to 100 records per poll, balancing throughput and memory pressure.
      properties:
        spring.json.trusted.packages: '*' # Allows JSON deserialization for incoming DTO classes.
    listener:
      concurrency: 6 # One concurrent consumer thread per partition target, enabling parallel processing.
      ack-mode: batch # Commits offsets after each consumed batch for efficient acknowledgment.
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
